### PR TITLE
Major cleanup and bugfixes. 

### PR DESCRIPTION
**Pull request by itchka**
Prevent the testing repo from being used by default
Rewrite front end $WORKDIR logic to ensure that if ABF=1 then users can't
run the program locally without setting the --debug option.
Give the $IN_ABF two states "0" and "1"
Fix misspelt CHGFLAG variable.
Rationalise and fix the localMd5Change function so that the CHNFLAG works
Add error channel dumping to CreatePkgLists to remove spurious
error message.
Fix misspelt variable in getIncFiles
Don't remove duplicate files in my.add and my.rmv, it's unecessary
Fix up xargs in mkUpdateChroot by adding "-n 1"
Fix the nonsense logic in createChroot.
Unmount the EFI $IMGNAME if mounted in umountall also supressed error
messages for missing mounts.
Substitute printf for the majority of error and informational messages and
tidy up presentation of same.
Remove additional from dracut conf

### CODE REVIEW

**Comment by tpgxyz** [comment]
@itchka Looks like final iso builded with this branch does have broken grub.cfg 
This is not a good sign.

Please check this file on ISO.
/boot/grub2/grub.conf

Released final iso does not carry our specific boot parameters. For example audit support is enabled and it bloats journald with usleless info, and drains battery.

I told you to not use this branch to build ISO, as it was not tested at all, and for me this branch brings nothing for end user.

**Comment by itchka** [comment]
Tomek
I merged everything from master before using cc_user_ver it  was done on the 
04/06/17 at this commit 657c01f87e4f6cc04d632764543516afc4db8f3d
I have just run a diff against my version to 3.0 and master and there's no 
mention of grub.cfg in there that would have this effect. Maybe your commit 
went wrong. On an installed system grub2 uses the files in /etc/grub/default as 
far as I'm aware to create grub.cfg when creating the boot loader so the 
problem would be in grub2 which I have not touched.
Finally though; if you check you will find that build 1180 which was the x86_64 
build released for 3.02 was built with 3.0.  See here https://
forum.openmandriva.org/t/actions-needing-for-omlx-3-02-release/1249/2

I used cc_user_branch to build the initial isos because it was the only one 
that would build i586 and indeed the final i586 iso was built with the 
cc_user_ver which has been greatly improved and has most if not all all the 
abf bugs fixed. fedya kindly showed me how to create an iso builder locally so 
I was able to debug the issues in the real environment instead of having to 
guess what was going on. Doing this allowed us to understand the problem of 
the missing /dev/loop devices  which was causing losetup to fail.  

I am at a loss as to what to say.
Best,
Colin

**Comment by tpgxyz** [comment]
@itchka  I'm talking about system booted from live ISO:

[root@localhost share]# cat /proc/cmdline 
BOOT_IMAGE=/boot/vmlinuz0 rootfstype=auto ro rd.luks=0 rd.lvm=0 rd.md=0 rd.dm=0 rd.live.image acpi_osi=Linux acpi_osi=!Windows root=live:UUID=2017-06-19-13-48-41-00 locale.lang=en_US quiet rhgb splash=silent


[root@localhost share]# file /boot/grub2/grub.cfg 
/boot/grub2/grub.cfg: empty

See here:
https://github.com/OpenMandrivaAssociation/omdv-build-iso/blob/master/omdv-build-iso.sh#L1237

**Comment by itchka** [comment]
Tomek
That line of code exists in all three versions.
I am unclear what the situation is here.  The grub.cfg file is being copied to 
the ISO directory ok but I am not clear whether /boot/grub2/grub.cfg should 
have anything in it anyway. Surely The system is after all not booted from the 
squashfs it's booted from start.cfg.
......
insmod minicmd
search.fs_uuid '%GRUB_UUID%' root
set prefix=($root)/boot/grub
configfile ($root)/boot/grub/grub.cfg
Which starts the kernel and the initrd the squashfs is mounted and extracted 
by the dracut scripts. What you have found implies that the kernel is booted a 
second time which seems a little unecessary.
It's easy enough to make everything at least look right by copying the 
grub.cfg to $CHROOTDIR/boot/grub2/grub.cfg.
I've done this and the file is not empty and proc/cmdline reports it's 
contents. I'm not sure though that it is honouring it as 
 I see this "rootfstype=auto ro" in the line but I am able to run urpmi --
auto-update  and install updates.

The current settings in the grub-bios.cfg do not switch off audit it is 
probably this we should update. 
Testing now and will let you know.
Colin

**Comment by itchka** [comment]
Tomek,
Should be fixed
Pushed commit to master
Colin

**Comment by itchka** [comment]
Didn't fix :(
Options must be being stripped by dracut or possibly xorriso or even mksquash 
fs
Don't know but will try to find out.
Colin

**Comment by tpgxyz** [comment]
@itchka  Can you please merge all changes from master to yours cc_user_ver branch ?
Then we may close this PR.

**Pull request merged**
